### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by kosuke-17** [kosuke-17/furima-34844#9]
自身のフリマアプリのURL
https://furima-34844.herokuapp.com/

Basic認証のIDとパスワード
ID: admin
パスワード: 2222

出品者用のメールアドレスとパスワード
メールアドレス：sample1@sample.com
パスワード：sample1

購入者用のメールアドレスとパスワード
メールアドレス：sample2@sample.com
パスワード：sample2

**Comment by runak25033** [comment]
ご提出ありがとうございます‼︎

問題なく正常に動作することが確認できました！　LGTMです✨　
おめでとうございます🎉
着実に技術力が身につき、実用的なアプリになってきてますね（^^）
最終課題発表会では、今までの成果を十分に発揮することができるよう、私達も応援しております🍀

**※確認したのは必須機能のみです。追加実装した機能については確認しておりません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるか、再度ご自身でご確認をお願い致します。**

<img width="916" alt="最終課題LGTM2" src="https://user-images.githubusercontent.com/79125420/111131649-cd9e1500-85bb-11eb-8efe-34dd72123da9.png">
